image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_TLS_CERTDIR: ""

stages:
  # - build
  - deploy

# build:
#   stage: build
#   script:
#     - docker info
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - echo 'build image ...'
#     - echo ${IMAGE_TAG}
#     - docker build -t "${IMAGE_TAG}" .
#     - docker push "${IMAGE_TAG}"
deploy_kubernetes:
  stage: deploy
  image: alpine:3.7
  environment:
    name: ${CI_COMMIT_REF_SLUG}
  script:
    - apk update && apk add bash
    - echo 'deploy k8s'
    - apk update  && apk add --no-cache curl grep
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p ${HOME}/.kube
    - echo $KUBECONFIG
    - echo $KUBECONFIG | $HOME/.kube/config
    - kubectl config view
    - kubectl version
    - kubectl get services -o wide


